# Generated by Django 4.0.6 on 2022-07-13 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('cooperativa', models.CharField(max_length=10)),
                ('numero', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=10)),
                ('imagen', models.ImageField(upload_to='img/%Y/%m/%d/')),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cantidad', models.IntegerField()),
                ('fecha_viaje', models.DateTimeField(auto_now_add=True)),
                ('efectivo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('comodo', 'Comodo'), ('incomodo', 'Incomodo')], default='', max_length=20)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSITUweb.bus')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSITUweb.pasajero')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('monto', models.CharField(max_length=3)),
                ('idPasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSITUweb.pasajero')),
            ],
        ),
        migrations.CreateModel(
            name='SimularAccesoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=7)),
                ('fecha_viaje', models.DateTimeField(auto_now_add=True)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSITUweb.tarjeta')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSITUweb.viaje')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='idTarjeta',
            field=models.ManyToManyField(through='appSITUweb.Viaje', to='appSITUweb.pasajero'),
        ),
    ]
